AUGMENTATION:
  aug_weight: 1.0
  confidence_threshold: 0.8
  pseudo_label_freq: 3
DATA:
  dataset_name: AID1798
  split_scheme: random_cv1
GENERAL:
  num_workers: 0
  seed: 1
MODEL:
  model_name: gcn
TRAIN:
  batch_size: 128
  early_stop: 100
  end_lr: 1e-6
  num_epochs: 100
  peak_lr: 1e-3
  warmup_iterations: 5000
  weight_decay: 1e-2
